# Generated by Django 5.1.1 on 2024-10-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.URLField(blank=True, null=True)),
                ('employment_type', models.CharField(max_length=100)),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('seniority', models.CharField(max_length=100)),
                ('location_restrictions', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone_restrictions', models.CharField(blank=True, max_length=255, null=True)),
                ('categories', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('application_link', models.URLField()),
                ('guid', models.URLField(unique=True)),
            ],
        ),
    ]
