# Generated by Django 5.1.1 on 2024-10-06 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remotive_job_id', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('company_logo', models.URLField(blank=True, null=True)),
                ('category', models.CharField(max_length=500)),
                ('job_type', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField()),
                ('candidate_required_location', models.CharField(blank=True, max_length=500, null=True)),
                ('salary', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='job.job')),
            ],
        ),
    ]
