# Generated by Django 5.1.1 on 2024-10-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
